name: Run tests on multi environment

on: push
jobs:
  macos_build:
    runs-on: macos-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build .

    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: macos_bin
        path: ./build/bin/sample

  windows_build:
    runs-on: windows-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: check
      run: vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
    - name: Build
      run: |
        powershell.exe -NoExit -Command "&{ $vsInstallPath=& "${env:ProgramFiles(x86)}/'Microsoft Visual Studio'/Installer/vswhere.exe" -prerelease -latest -property installationPath; Import-Module "$vsInstallPath/Common7/Tools/Microsoft.VisualStudio.DevShell.dll"; Enter-VsDevShell -VsInstallPath $vsInstallPath -SkipAutomaticLocation }"
        CL .\main.c gdi32.lib /link /OUT:dtan.exe
        ls
        gcc ./main.c -o dtan.exe -lgdi32
        ls
        mkdir -p build && cd build && cmake .. && cmake --build . --config Release

    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: windows_bin
        path: ./build/bin/Release/sample.exe
