name: Run tests on multi environment

on: push
jobs:
  macos_build:
    runs-on: macos-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build .

    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: macos_bin
        path: ./build/bin/sample

  windows_build:
    runs-on: windows-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: |
        CL.exe .\main.c gdi32.lib /link /OUT:dtan.exe
        ls
        gcc ./main.c -o dtan.exe -lgdi32
        ls
        mkdir -p build && cd build && cmake .. && cmake --build . --config Release

    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: windows_bin
        path: ./build/bin/Release/sample.exe
