name: BuildSample

on:
  repository_dispatch:
    types: [build]
  push:
    branches:
      - '*'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:

    - name: Build Step
      id: hello
      uses: actions/hello-world-docker-action@v1
      with:
        who-to-greet: 'Mona the Octocat'

    - name: Test Step
      run: echo "The time was ${{ steps.hello.outputs.time }}"

    - name: Upload Step
      run: echo "The time was ${{ steps.hello.outputs.time }}"

    - name: Get github event action
      run: echo "${{ github.event.action }}"

    - name: Get client_payload
      run: echo "${{ toJSON(github.event.client_payload) }}"
