name: Example workflow

on: [push, deployment]
  

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:

    - name: Build Step
      id: hello
      uses: actions/hello-world-docker-action@v1
      with:
        who-to-greet: 'Mona the Octocat'

    - name: Test Step
      run: echo "The time was ${{ steps.hello.outputs.time }}"

    - name: Upload Step
      run: echo "The time was ${{ steps.hello.outputs.time }}"

    - name: Get github info
      run: echo "${{ toJSON(github.event) }}"

    - name: Get github info
      run: test "${{ toJSON(github.event.description) }}" == "null" && echo "desk is ${{ toJSON(github.event.description) }}"  || echo null
