# Actionの名前
name: Sample

# Jobが実行されるトリガー
# pushされた場合、もしくはイベント種別が「hoge」のリポジトリディスパッチイベントが作成された場合に実行する
on:
  push:
  repository_dispatch:
    types: [hoge]

jobs:
  sample_job:
    runs-on: ubuntu-latest
    name: sample_job
    steps:
      - uses: actions/checkout@v1

      # ブランチが指定されていた場合は、指定されているブランチを利用する
      - if: github.event.client_payload
        uses: actions/checkout@v1
        with:
          ref: ${{ github.event.client_payload.ref }}

      # echo_string
      - if: github.event.client_payload.echo_string
        name: echo string
        run: echo ${{ toJSON(github.event.client_payload.echo_string) }}