name: Sample
on: push

jobs:

  main_job:
    defaults:
      run:
        working-directory: .
    runs-on: ubuntu-latest
    steps:
      - name: make aaaa.txt
        run: echo aaaa > aaaa.txt

  sub_job:
    runs-on: ubuntu-latest
    steps:
      - name: make bbbb.txt
        run: echo bbbb > bbbb.txt

  next_job:
    needs:
      - main_job
      - sub_job
    runs-on: ubuntu-latest
    steps:
      - name: cat txt
        run: |
          cat aaaa.txt
          cat bbbb.txt
