name: Sample
on: push

jobs:

  main_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo aaaa > aaaa.txt
      - uses: actions/upload-artifact@v3
        with:
          name: aaaa
          path: aaaa.txt

  sub_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo bbbb > bbbb.txt
      - uses: actions/upload-artifact@v3
        with:
          name: bbbb
          path: bbbb.txt

  next_job:
    needs:
      - main_job
      - sub_job
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v3

      - name: cat txt
        run: |
          ls -al
          cat ./aaaa/aaaa.txt
          cat ./bbbb/bbbb.txt
