name: Sample

on:
  push:
  repository_dispatch:
    types: [hoge]
jobs:
  hoge:
    runs-on: ubuntu-latest
    name: hoge
    steps:
      - uses: actions/checkout@v1

      - if: github.event.client_payload
        uses: actions/checkout@v1
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Get github info
        run: ls -al

      - name: Get github info
        run: echo "${{ toJSON(github.event.ref) }}"

      - name: Get github info
        run: echo_string="${{ toJSON(github.event.client_payload.echo_string) }}" && test "$echo_string" == "null" && echo null || echo "desk is $echo_string"
