# Actionの名前
name: Pull

on:
  push:

jobs:
  sample_job:
    runs-on: ubuntu-latest
    container:
      image: centos:latest
    name: sample_job
    steps:
      - uses: actions/checkout@v1

      # echo_string
      - name: dnf --version
        run: dnf --version